using System.Numerics;

namespace EIV_Pack.Test;

public class UnmanagedTests
{
    [Fact]
    public void UnmangedTest()
    {
        PackWriter writer = new();
        writer.WriteUnmanaged(true);
        writer.WriteUnmanaged(false);
        writer.WriteUnmanaged(byte.MinValue);
        writer.WriteUnmanaged(byte.MaxValue);
        writer.WriteUnmanaged(sbyte.MinValue);
        writer.WriteUnmanaged(sbyte.MaxValue);
        writer.WriteUnmanaged(short.MinValue);
        writer.WriteUnmanaged(short.MaxValue);
        writer.WriteUnmanaged(ushort.MinValue);
        writer.WriteUnmanaged(ushort.MaxValue);
        writer.WriteUnmanaged(int.MinValue);
        writer.WriteUnmanaged(int.MaxValue);
        writer.WriteUnmanaged(uint.MinValue);
        writer.WriteUnmanaged(uint.MaxValue);
        writer.WriteUnmanaged(long.MinValue);
        writer.WriteUnmanaged(long.MaxValue);
        writer.WriteUnmanaged(ulong.MinValue);
        writer.WriteUnmanaged(ulong.MaxValue);
        writer.WriteUnmanaged(Int128.MinValue);
        writer.WriteUnmanaged(Int128.MaxValue);
        writer.WriteUnmanaged(UInt128.MinValue);
        writer.WriteUnmanaged(UInt128.MaxValue);
        writer.WriteUnmanaged(char.MinValue);
        writer.WriteUnmanaged(char.MaxValue);
        writer.WriteUnmanaged(float.MinValue);
        writer.WriteUnmanaged(float.MaxValue);
        writer.WriteUnmanaged(double.MinValue);
        writer.WriteUnmanaged(double.MaxValue);
        writer.WriteUnmanaged(decimal.MinValue);
        writer.WriteUnmanaged(decimal.MaxValue);
        writer.WriteUnmanaged(IntPtr.MinValue);
        writer.WriteUnmanaged(IntPtr.MaxValue);
        writer.WriteUnmanaged(UIntPtr.MinValue);
        writer.WriteUnmanaged(UIntPtr.MaxValue);
        writer.WriteUnmanaged(DateTime.MinValue);
        writer.WriteUnmanaged(DateTime.MaxValue);
        writer.WriteUnmanaged(DateTimeOffset.MinValue);
        writer.WriteUnmanaged(DateTimeOffset.MaxValue);
        writer.WriteUnmanaged(TimeSpan.MinValue);
        writer.WriteUnmanaged(TimeSpan.MaxValue);
        writer.WriteUnmanaged(DateOnly.MinValue);
        writer.WriteUnmanaged(DateOnly.MaxValue);
        writer.WriteUnmanaged(TimeOnly.MinValue);
        writer.WriteUnmanaged(TimeOnly.MaxValue);
        writer.WriteUnmanaged(Matrix3x2.Identity);
        writer.WriteUnmanaged(Matrix4x4.Identity);
        writer.WriteUnmanaged(Quaternion.Identity);
        writer.WriteUnmanaged(Vector2.Zero);
        writer.WriteUnmanaged(Vector3.Zero);
        writer.WriteUnmanaged(Vector4.Zero);
        writer.WriteUnmanaged(Complex.Zero);
        writer.WriteUnmanaged(Guid.Empty);
        var bytes = writer.GetBytes();
        Assert.NotEmpty(bytes);
        PackReader reader = new(bytes);
        Assert.True(reader.ReadUnmanaged<bool>());
        Assert.False(reader.ReadUnmanaged<bool>());
        Assert.Equal(byte.MinValue, reader.ReadUnmanaged<byte>());
        Assert.Equal(byte.MaxValue, reader.ReadUnmanaged<byte>());
        Assert.Equal(sbyte.MinValue, reader.ReadUnmanaged<sbyte>());
        Assert.Equal(sbyte.MaxValue, reader.ReadUnmanaged<sbyte>());
        Assert.Equal(short.MinValue, reader.ReadUnmanaged<short>());
        Assert.Equal(short.MaxValue, reader.ReadUnmanaged<short>());
        Assert.Equal(ushort.MinValue, reader.ReadUnmanaged<ushort>());
        Assert.Equal(ushort.MaxValue, reader.ReadUnmanaged<ushort>());
        Assert.Equal(int.MinValue, reader.ReadUnmanaged<int>());
        Assert.Equal(int.MaxValue, reader.ReadUnmanaged<int>());
        Assert.Equal(uint.MinValue, reader.ReadUnmanaged<uint>());
        Assert.Equal(uint.MaxValue, reader.ReadUnmanaged<uint>());
        Assert.Equal(long.MinValue, reader.ReadUnmanaged<long>());
        Assert.Equal(long.MaxValue, reader.ReadUnmanaged<long>());
        Assert.Equal(ulong.MinValue, reader.ReadUnmanaged<ulong>());
        Assert.Equal(ulong.MaxValue, reader.ReadUnmanaged<ulong>());
        Assert.Equal(Int128.MinValue, reader.ReadUnmanaged<Int128>());
        Assert.Equal(Int128.MaxValue, reader.ReadUnmanaged<Int128>());
        Assert.Equal(UInt128.MinValue, reader.ReadUnmanaged<UInt128>());
        Assert.Equal(UInt128.MaxValue, reader.ReadUnmanaged<UInt128>());
        Assert.Equal(char.MinValue, reader.ReadUnmanaged<char>());
        Assert.Equal(char.MaxValue, reader.ReadUnmanaged<char>());
        Assert.Equal(float.MinValue, reader.ReadUnmanaged<float>());
        Assert.Equal(float.MaxValue, reader.ReadUnmanaged<float>());
        Assert.Equal(double.MinValue, reader.ReadUnmanaged<double>());
        Assert.Equal(double.MaxValue, reader.ReadUnmanaged<double>());
        Assert.Equal(decimal.MinValue, reader.ReadUnmanaged<decimal>());
        Assert.Equal(decimal.MaxValue, reader.ReadUnmanaged<decimal>());
        Assert.Equal(IntPtr.MinValue, reader.ReadUnmanaged<IntPtr>());
        Assert.Equal(IntPtr.MaxValue, reader.ReadUnmanaged<IntPtr>());
        Assert.Equal(UIntPtr.MinValue, reader.ReadUnmanaged<UIntPtr>());
        Assert.Equal(UIntPtr.MaxValue, reader.ReadUnmanaged<UIntPtr>());
        Assert.Equal(DateTime.MinValue, reader.ReadUnmanaged<DateTime>());
        Assert.Equal(DateTime.MaxValue, reader.ReadUnmanaged<DateTime>());
        Assert.Equal(DateTimeOffset.MinValue, reader.ReadUnmanaged<DateTimeOffset>());
        Assert.Equal(DateTimeOffset.MaxValue, reader.ReadUnmanaged<DateTimeOffset>());
        Assert.Equal(TimeSpan.MinValue, reader.ReadUnmanaged<TimeSpan>());
        Assert.Equal(TimeSpan.MaxValue, reader.ReadUnmanaged<TimeSpan>());
        Assert.Equal(DateOnly.MinValue, reader.ReadUnmanaged<DateOnly>());
        Assert.Equal(DateOnly.MaxValue, reader.ReadUnmanaged<DateOnly>());
        Assert.Equal(TimeOnly.MinValue, reader.ReadUnmanaged<TimeOnly>());
        Assert.Equal(TimeOnly.MaxValue, reader.ReadUnmanaged<TimeOnly>());
        Assert.Equal(Matrix3x2.Identity, reader.ReadUnmanaged<Matrix3x2>());
        Assert.Equal(Matrix4x4.Identity, reader.ReadUnmanaged<Matrix4x4>());
        Assert.Equal(Quaternion.Identity, reader.ReadUnmanaged<Quaternion>());
        Assert.Equal(Vector2.Zero, reader.ReadUnmanaged<Vector2>());
        Assert.Equal(Vector3.Zero, reader.ReadUnmanaged<Vector3>());
        Assert.Equal(Vector4.Zero, reader.ReadUnmanaged<Vector4>());
        Assert.Equal(Complex.Zero, reader.ReadUnmanaged<Complex>());
        Assert.Equal(Guid.Empty, reader.ReadUnmanaged<Guid>());
        Assert.Equal(0, reader.Remaining);
    }

    [Fact]
    public void UnmangedNullableTest()
    {
        PackWriter writer = new();
        writer.WriteUnmanagedNullable<bool>(true);
        writer.WriteUnmanagedNullable<bool>(false);
        writer.WriteUnmanagedNullable<byte>(byte.MinValue);
        writer.WriteUnmanagedNullable<byte>(byte.MaxValue);
        writer.WriteUnmanagedNullable<sbyte>(sbyte.MinValue);
        writer.WriteUnmanagedNullable<sbyte>(sbyte.MaxValue);
        writer.WriteUnmanagedNullable<short>(short.MinValue);
        writer.WriteUnmanagedNullable<short>(short.MaxValue);
        writer.WriteUnmanagedNullable<ushort>(ushort.MinValue);
        writer.WriteUnmanagedNullable<ushort>(ushort.MaxValue);
        writer.WriteUnmanagedNullable<int>(int.MinValue);
        writer.WriteUnmanagedNullable<int>(int.MaxValue);
        writer.WriteUnmanagedNullable<uint>(uint.MinValue);
        writer.WriteUnmanagedNullable<uint>(uint.MaxValue);
        writer.WriteUnmanagedNullable<long>(long.MinValue);
        writer.WriteUnmanagedNullable<long>(long.MaxValue);
        writer.WriteUnmanagedNullable<ulong>(ulong.MinValue);
        writer.WriteUnmanagedNullable<ulong>(ulong.MaxValue);
        writer.WriteUnmanagedNullable<Int128>(Int128.MinValue);
        writer.WriteUnmanagedNullable<Int128>(Int128.MaxValue);
        writer.WriteUnmanagedNullable<UInt128>(UInt128.MinValue);
        writer.WriteUnmanagedNullable<UInt128>(UInt128.MaxValue);
        writer.WriteUnmanagedNullable<char>(char.MinValue);
        writer.WriteUnmanagedNullable<char>(char.MaxValue);
        writer.WriteUnmanagedNullable<float>(float.MinValue);
        writer.WriteUnmanagedNullable<float>(float.MaxValue);
        writer.WriteUnmanagedNullable<double>(double.MinValue);
        writer.WriteUnmanagedNullable<double>(double.MaxValue);
        writer.WriteUnmanagedNullable<decimal>(decimal.MinValue);
        writer.WriteUnmanagedNullable<decimal>(decimal.MaxValue);
        writer.WriteUnmanagedNullable<IntPtr>(IntPtr.MinValue);
        writer.WriteUnmanagedNullable<IntPtr>(IntPtr.MaxValue);
        writer.WriteUnmanagedNullable<UIntPtr>(UIntPtr.MinValue);
        writer.WriteUnmanagedNullable<UIntPtr>(UIntPtr.MaxValue);
        writer.WriteUnmanagedNullable<DateTime>(DateTime.MinValue);
        writer.WriteUnmanagedNullable<DateTime>(DateTime.MaxValue);
        writer.WriteUnmanagedNullable<DateTimeOffset>(DateTimeOffset.MinValue);
        writer.WriteUnmanagedNullable<DateTimeOffset>(DateTimeOffset.MaxValue);
        writer.WriteUnmanagedNullable<TimeSpan>(TimeSpan.MinValue);
        writer.WriteUnmanagedNullable<TimeSpan>(TimeSpan.MaxValue);
        writer.WriteUnmanagedNullable<DateOnly>(DateOnly.MinValue);
        writer.WriteUnmanagedNullable<DateOnly>(DateOnly.MaxValue);
        writer.WriteUnmanagedNullable<TimeOnly>(TimeOnly.MinValue);
        writer.WriteUnmanagedNullable<TimeOnly>(TimeOnly.MaxValue);
        writer.WriteUnmanagedNullable<Matrix3x2>(Matrix3x2.Identity);
        writer.WriteUnmanagedNullable<Matrix4x4>(Matrix4x4.Identity);
        writer.WriteUnmanagedNullable<Quaternion>(Quaternion.Identity);
        writer.WriteUnmanagedNullable<Vector2>(Vector2.Zero);
        writer.WriteUnmanagedNullable<Vector3>(Vector3.Zero);
        writer.WriteUnmanagedNullable<Vector4>(Vector4.Zero);
        writer.WriteUnmanagedNullable<Complex>(Complex.Zero);
        writer.WriteUnmanagedNullable<Guid>(Guid.Empty);
        var bytes = writer.GetBytes();
        Assert.NotEmpty(bytes);
        PackReader reader = new(bytes);
        Assert.True(reader.ReadUnmanagedNullable<bool>());
        Assert.False(reader.ReadUnmanagedNullable<bool>());
        Assert.Equal(byte.MinValue, reader.ReadUnmanagedNullable<byte>());
        Assert.Equal(byte.MaxValue, reader.ReadUnmanagedNullable<byte>());
        Assert.Equal(sbyte.MinValue, reader.ReadUnmanagedNullable<sbyte>());
        Assert.Equal(sbyte.MaxValue, reader.ReadUnmanagedNullable<sbyte>());
        Assert.Equal(short.MinValue, reader.ReadUnmanagedNullable<short>());
        Assert.Equal(short.MaxValue, reader.ReadUnmanagedNullable<short>());
        Assert.Equal(ushort.MinValue, reader.ReadUnmanagedNullable<ushort>());
        Assert.Equal(ushort.MaxValue, reader.ReadUnmanagedNullable<ushort>());
        Assert.Equal(int.MinValue, reader.ReadUnmanagedNullable<int>());
        Assert.Equal(int.MaxValue, reader.ReadUnmanagedNullable<int>());
        Assert.Equal(uint.MinValue, reader.ReadUnmanagedNullable<uint>());
        Assert.Equal(uint.MaxValue, reader.ReadUnmanagedNullable<uint>());
        Assert.Equal(long.MinValue, reader.ReadUnmanagedNullable<long>());
        Assert.Equal(long.MaxValue, reader.ReadUnmanagedNullable<long>());
        Assert.Equal(ulong.MinValue, reader.ReadUnmanagedNullable<ulong>());
        Assert.Equal(ulong.MaxValue, reader.ReadUnmanagedNullable<ulong>());
        Assert.Equal(Int128.MinValue, reader.ReadUnmanagedNullable<Int128>());
        Assert.Equal(Int128.MaxValue, reader.ReadUnmanagedNullable<Int128>());
        Assert.Equal(UInt128.MinValue, reader.ReadUnmanagedNullable<UInt128>());
        Assert.Equal(UInt128.MaxValue, reader.ReadUnmanagedNullable<UInt128>());
        Assert.Equal(char.MinValue, reader.ReadUnmanagedNullable<char>());
        Assert.Equal(char.MaxValue, reader.ReadUnmanagedNullable<char>());
        Assert.Equal(float.MinValue, reader.ReadUnmanagedNullable<float>());
        Assert.Equal(float.MaxValue, reader.ReadUnmanagedNullable<float>());
        Assert.Equal(double.MinValue, reader.ReadUnmanagedNullable<double>());
        Assert.Equal(double.MaxValue, reader.ReadUnmanagedNullable<double>());
        Assert.Equal(decimal.MinValue, reader.ReadUnmanagedNullable<decimal>());
        Assert.Equal(decimal.MaxValue, reader.ReadUnmanagedNullable<decimal>());
        Assert.Equal(IntPtr.MinValue, reader.ReadUnmanagedNullable<IntPtr>());
        Assert.Equal(IntPtr.MaxValue, reader.ReadUnmanagedNullable<IntPtr>());
        Assert.Equal(UIntPtr.MinValue, reader.ReadUnmanagedNullable<UIntPtr>());
        Assert.Equal(UIntPtr.MaxValue, reader.ReadUnmanagedNullable<UIntPtr>());
        Assert.Equal(DateTime.MinValue, reader.ReadUnmanagedNullable<DateTime>());
        Assert.Equal(DateTime.MaxValue, reader.ReadUnmanagedNullable<DateTime>());
        Assert.Equal(DateTimeOffset.MinValue, reader.ReadUnmanagedNullable<DateTimeOffset>());
        Assert.Equal(DateTimeOffset.MaxValue, reader.ReadUnmanagedNullable<DateTimeOffset>());
        Assert.Equal(TimeSpan.MinValue, reader.ReadUnmanagedNullable<TimeSpan>());
        Assert.Equal(TimeSpan.MaxValue, reader.ReadUnmanagedNullable<TimeSpan>());
        Assert.Equal(DateOnly.MinValue, reader.ReadUnmanagedNullable<DateOnly>());
        Assert.Equal(DateOnly.MaxValue, reader.ReadUnmanagedNullable<DateOnly>());
        Assert.Equal(TimeOnly.MinValue, reader.ReadUnmanagedNullable<TimeOnly>());
        Assert.Equal(TimeOnly.MaxValue, reader.ReadUnmanagedNullable<TimeOnly>());
        Assert.Equal(Matrix3x2.Identity, reader.ReadUnmanagedNullable<Matrix3x2>());
        Assert.Equal(Matrix4x4.Identity, reader.ReadUnmanagedNullable<Matrix4x4>());
        Assert.Equal(Quaternion.Identity, reader.ReadUnmanagedNullable<Quaternion>());
        Assert.Equal(Vector2.Zero, reader.ReadUnmanagedNullable<Vector2>());
        Assert.Equal(Vector3.Zero, reader.ReadUnmanagedNullable<Vector3>());
        Assert.Equal(Vector4.Zero, reader.ReadUnmanagedNullable<Vector4>());
        Assert.Equal(Complex.Zero, reader.ReadUnmanagedNullable<Complex>());
        Assert.Equal(Guid.Empty, reader.ReadUnmanagedNullable<Guid>());
        Assert.Equal(0, reader.Remaining);
    }

    [Fact]
    public void UnmangedValueTest()
    {
        PackWriter writer = new();
        writer.WriteValue<int?>(666);
        writer.WriteValue<int>(666);
        var bytes = writer.GetBytes();
        Assert.NotEmpty(bytes);
        PackReader reader = new(bytes);
        Assert.Equal(666, reader.ReadValue<int?>());
        Assert.Equal(666, reader.ReadValue<int>());
        Assert.Equal(0, reader.Remaining);
    }

    [Fact]
    public void UnmanagedArrayTest()
    {
        int?[] vals = [666, 6667, null, 6];
        PackWriter writer = new();
        writer.WriteArray<int?>([]);
        writer.WriteArray<int?>(null);
        writer.WriteArray<int?>(vals);
        var bytes = writer.GetBytes();
        Assert.NotEmpty(bytes);
        PackReader reader = new(bytes);
        Assert.Empty(reader.ReadArray<int?>()!);
        Assert.Null(reader.ReadArray<int?>());
        Assert.Equal(vals, reader.ReadArray<int?>());
        Assert.Equal(0, reader.Remaining);
    }
}
